### ISSUE TITLE
pylibdmtx non-deterministic behaviour?

### ISSUE THREAD

**Issue by bsdis** [NaturalHistoryMuseum/pylibdmtx#48]
When i run the following simple snippet many times:
```
from pylibdmtx.pylibdmtx import encode
from pylibdmtx.pylibdmtx import decode
from PIL import Image
encstr = '1111111111'
encoded = encode(encstr)
img = Image.frombytes('RGB', (encoded.width, encoded.height), encoded.pixels)
print(decode(img)[0].data)
```
I see that the output resultat very often is different and its never the same as the input.

Am I totally misunderstanding a datamatrix concept here or are there major errors in this library?

**Comment by bsdis** [comment]
needs to be encoded

**Comment by niniack** [comment]
I'm running into the same issue, could you help me see what the key to the issue was? Thanks!

**Comment by bsdis** [comment]
yeah - essentially pydmtx needs a bytestring, so a string like `encstr` in my example above needs to be encoded before supplied to the encoder, so `encode(encstr.encode())`
