### ISSUE TITLE
How do I decode low quality image

### ISSUE THREAD

**Issue by CurssedCoffin** [NaturalHistoryMuseum/pylibdmtx#77]
I have images in low quality like this. Could anyone help me to decode such images?
![mmexport1642751370588](https://user-images.githubusercontent.com/49067137/150503547-31c8ef5f-1c3e-49d5-aa6f-a8706ff426ef.png)
This image is shot in dark environment but the main content is still good i think.
I have tried to light it up and change the contrast but cannot decode it.

**Comment by MathijsNL** [comment]
I was able to scan it once, you know what the code should be for the image you posted?

I am getting this:
CR114761X9E0T3XAC 

Gimp has a tool for color curves. Screenshot below shows the curve I used to get the result (with app on my phone)
![image](https://user-images.githubusercontent.com/1612886/168695784-c11b4c02-82d4-4782-a116-e5429a36b6ad.png)

If you find a way to do that in OpenCV you should be able to scan the codes.

**Comment by CurssedCoffin** [comment]
Thanks dude. Maybe color curves is a good solution to this problem. Thank you.
