### ISSUE TITLE
Package 'libdmtx0a' has no installation candidate

### ISSUE THREAD

**Issue by lsx1980** [NaturalHistoryMuseum/pylibdmtx#82]
sudo apt-get install libdmtx0a

has an error on Ubuntu 20
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libdmtx0a is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libdmtx0b

Tried with sudo apt-get install libdmtx0b
works now

**Comment by Hassan-Mallah** [comment]
Thanks, worked for me too
